# Welcome to Jekyll!
#

# Site settings
title: YAuth.jp
description: |
  Consulting Company around Digital Identity Technology by [Nov Matake](http://matake.jp)
owner: YAuth.jp
first_published: 2016 # if migrating another site, the year of your first publish
email: nov@yauth.jp
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yauth.jp" # the base hostname & protocol for your site
external_links:
  - matakejp:
    title: matake.jp
    url: http://matake.jp
  - oauthjp:
    title: OAuth.jp
    url: http://oauth.jp
  - idcon:
    title: idcon.org
    url: http://idcon.org
social:
  twitter: https://twitter.com/nov
  facebook-official: https://facebook.com/matake
  linkedin-square: https://linkedin.com/in/novmatake
  github: https://github.com/nov
  slideshare: http://www.slideshare.net/matake/presentations
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
