# Welcome to Jekyll!
#

# Theme: http://jekyllthemes.org/themes/spectral/

# Site settings
title: YAuth.jp
description: |
  Digital Identity Specialist - [Nov Matake](http://matake.jp)
owner: YAuth.jp
first_published: 2016 # if migrating another site, the year of your first publish
email: nov@yauth.jp
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yauth.jp" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/nov
  facebook-official: https://facebook.com/matake
  linkedin-square: https://linkedin.com/in/novmatake
  github: https://github.com/nov
  slideshare: http://www.slideshare.net/matake/presentations
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
